<?php

namespace RPGBundle\Repository;

/**
 * savedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class savedRepository extends \Doctrine\ORM\EntityRepository
{
}
